# -*- coding: utf-8 -*-
"""Codtech task-4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13raEmeEZEFlTCWb_PwHywfI7Cpj3YTrS
"""

!pip install pulp

from pulp import *

# Create the LP problem
model = LpProblem("Product_Mix_Optimization", LpMaximize)

# Define decision variables
# x = units of Product A
# y = units of Product B

x = LpVariable('Product_A', lowBound=0)
y = LpVariable('Product_B', lowBound=0)

# Profit: Product A = 40, Product B = 30
model += 40*x + 30*y, "Total_Profit"

# Constraints:
# 1. Labor constraint
model += 2*x + y <= 100

# 2. Material constraint
model += x + y <= 80

model.solve()

print("Status:", LpStatus[model.status])
print("Optimal Production Plan:")
print("Product A =", value(x))
print("Product B =", value(y))
print("Maximum Profit =", value(model.objective))

import matplotlib.pyplot as plt
import numpy as np

# Plot constraints
x_vals = np.linspace(0, 100, 100)

y1 = 100 - 2*x_vals   # from 2x + y = 100
y2 = 80 - x_vals      # from x + y = 80

plt.plot(x_vals, y1, label='2x + y = 100')
plt.plot(x_vals, y2, label='x + y = 80')

plt.xlabel("Product A")
plt.ylabel("Product B")
plt.title("Feasible Region")
plt.legend()
plt.grid()

plt.show()